# Generated by Django 5.2.17 on 2026-08-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesettings',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
