# Generated by Django 5.2.17 on 2026-08-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('changes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_group', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=200)),
                ('competitors', models.CharField(default='All competitors', max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('frequency', models.CharField(default='Immediate', max_length=40)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('pattern_based', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed')], default='new', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('change_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='changes.changeevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.workspace')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['workspace', 'enabled'], name='alerts_aler_workspa_2359f3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', '-triggered_at'], name='alerts_aler_workspa_1a21e5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'status'], name='alerts_aler_workspa_35f8ef_idx'),
        ),
    ]
