# Generated by Django 5.2.17 on 2026-08-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('cluster', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('monitoring', 'Monitoring'), ('dismissed', 'Dismissed')], default='suggested', max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('catalogue_profile', models.JSONField(blank=True, default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_candidates', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-score', 'name'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='discovery_d_workspa_ecdc7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_discovery_candidate_slug')],
            },
        ),
    ]
