# Generated by Django 5.2.17 on 2026-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('price_increase', 'Price increase'), ('price_decrease', 'Price decrease'), ('stock_in', 'Stock in'), ('stock_out', 'Stock out'), ('product_new', 'New product'), ('product_removed', 'Removed product'), ('promotion_started', 'Promotion started'), ('promotion_ended', 'Promotion ended'), ('product_metadata_change', 'Product metadata change')], max_length=40)),
                ('kind', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('previous_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('secondary', models.CharField(blank=True, max_length=60)),
                ('secondary_tone', models.CharField(blank=True, max_length=20)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('difference', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
