# Generated by Django 5.2.17 on 2026-08-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0002_initial'),
        ('changes', '0001_initial'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeevent',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='competitors.competitor'),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='catalogue.productlisting'),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['workspace', '-detected_at'], name='changes_cha_workspa_c425d3_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['workspace', 'event_type'], name='changes_cha_workspa_7fda68_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['competitor', '-detected_at'], name='changes_cha_competi_b09a05_idx'),
        ),
    ]
