"""Mock data ported from prototype-react/src/lib/products-data.ts — deterministic seed for Phase 1."""

PRODUCT_COUNT = 8746

PRODUCTS = [
    {
        "slug": "lego-castle-set",
        "name": "LEGO Castle Set",
        "sku": "TW-10432",
        "tone": "info",
        "competitor": "ToyWorld.co.uk",
        "category": "Construction Toys",
        "current_price": 49.99,
        "previous_price": 59.99,
        "change": {"kind": "drop", "label": "-16.7%"},
        "in_stock": True,
        "last_change": "2h ago",
        "last_change_minutes": 120,
        "discovered_at": "2026-03-04",
        "source_url": "https://toyworld.co.uk/products/lego-castle-set",
        "image": "img/products/lego-castle-set.svg",
        "matched": {
            "count": 3,
            "confidence": 96,
            "insight": "ToyWorld is currently £2.49 more expensive than the lowest detected competitor with available stock.",
            "listings": [
                {"competitor": "ToyWorld.co.uk", "price": 49.99, "in_stock": True, "promotion": None, "last_scan": "12m ago"},
                {"competitor": "PlayNest.co.uk", "price": 52.99, "in_stock": True, "promotion": "10% off", "last_scan": "26m ago"},
                {"competitor": "HappyToyHouse.com", "price": 47.5, "in_stock": False, "promotion": None, "last_scan": "1h ago"},
            ],
        },
    },
    {
        "slug": "stem-robot-kit",
        "name": "STEM Robot Kit",
        "sku": "TW-20871",
        "tone": "purple",
        "competitor": "ToyWorld.co.uk",
        "category": "Educational Toys",
        "current_price": 39.99,
        "previous_price": 39.99,
        "change": {"kind": "promo", "label": "20% promotion"},
        "in_stock": True,
        "last_change": "3h ago",
        "last_change_minutes": 180,
        "discovered_at": "2026-03-11",
        "source_url": "https://toyworld.co.uk/products/stem-robot-kit",
        "image": "img/products/stem-robot-kit.svg",
    },
    {
        "slug": "wooden-balance-bike",
        "name": "Wooden Balance Bike",
        "sku": "TW-30114",
        "tone": "warning",
        "competitor": "ToyWorld.co.uk",
        "category": "Outdoor Toys",
        "current_price": 89,
        "previous_price": 89,
        "change": {"kind": "oos", "label": "Out of stock"},
        "in_stock": False,
        "last_change": "4h ago",
        "last_change_minutes": 240,
        "discovered_at": "2026-04-02",
        "source_url": "https://toyworld.co.uk/products/wooden-balance-bike",
        "image": "img/products/wooden-balance-bike.svg",
    },
    {
        "slug": "unicorn-plush-xl",
        "name": "Unicorn Plush XL",
        "sku": "PN-88214",
        "tone": "rose",
        "competitor": "PlayNest.co.uk",
        "category": "Plush Toys",
        "current_price": 24.99,
        "previous_price": None,
        "change": {"kind": "new", "label": "New product"},
        "in_stock": True,
        "last_change": "6h ago",
        "last_change_minutes": 360,
        "discovered_at": "2026-08-25",
        "source_url": "https://playnest.co.uk/products/unicorn-plush-xl",
        "image": "img/products/unicorn-plush-xl.svg",
    },
    {
        "slug": "personalised-puzzle",
        "name": "Personalised Puzzle",
        "sku": "HM-50963",
        "tone": "teal",
        "competitor": "HappyToyHouse.com",
        "category": "Personalised Toys",
        "current_price": 19.99,
        "previous_price": 19.99,
        "change": {"kind": "name", "label": "Name changed"},
        "in_stock": True,
        "last_change": "8h ago",
        "last_change_minutes": 480,
        "discovered_at": "2026-04-19",
        "source_url": "https://happytoyhouse.com/products/personalised-puzzle",
        "image": "img/products/personalised-puzzle.svg",
    },
    {
        "slug": "garden-water-table",
        "name": "Garden Water Table",
        "sku": "PN-11302",
        "tone": "info",
        "competitor": "PlayNest.co.uk",
        "category": "Outdoor Toys",
        "current_price": 64.99,
        "previous_price": 59.99,
        "change": {"kind": "increase", "label": "+8.3%"},
        "in_stock": True,
        "last_change": "9h ago",
        "last_change_minutes": 540,
        "discovered_at": "2026-05-07",
        "source_url": "https://playnest.co.uk/products/garden-water-table",
        "image": "img/products/garden-water-table.svg",
    },
    {
        "slug": "baby-sensory-gym",
        "name": "Baby Sensory Gym",
        "sku": "LM-70415",
        "tone": "purple",
        "competitor": "LittleMindsToys.co.uk",
        "category": "Baby Toys",
        "current_price": 44.5,
        "previous_price": 44.5,
        "change": {"kind": "back", "label": "Back in stock"},
        "in_stock": True,
        "last_change": "11h ago",
        "last_change_minutes": 660,
        "discovered_at": "2026-05-22",
        "source_url": "https://littlemindstoys.co.uk/products/baby-sensory-gym",
        "image": "img/products/baby-sensory-gym.svg",
    },
    {
        "slug": "dinosaur-excavation-kit",
        "name": "Dinosaur Excavation Kit",
        "sku": "HM-61220",
        "tone": "warning",
        "competitor": "HappyToyHouse.com",
        "category": "Educational Toys",
        "current_price": 14.99,
        "previous_price": 14.99,
        "change": {"kind": "removed", "label": "Removed"},
        "in_stock": False,
        "last_change": "1d ago",
        "last_change_minutes": 1440,
        "discovered_at": "2026-03-28",
        "source_url": "https://happytoyhouse.com/products/dinosaur-excavation-kit",
        "image": "img/products/dinosaur-excavation-kit.svg",
    },
    {
        "slug": "wooden-train-set",
        "name": "Wooden Train Set",
        "sku": "LM-33871",
        "tone": "teal",
        "competitor": "LittleMindsToys.co.uk",
        "category": "Construction Toys",
        "current_price": 32.99,
        "previous_price": 32.99,
        "change": {"kind": "category", "label": "Category changed"},
        "in_stock": True,
        "last_change": "1d ago",
        "last_change_minutes": 1500,
        "discovered_at": "2026-06-15",
        "source_url": "https://littlemindstoys.co.uk/products/wooden-train-set",
        "image": None,  # fallback exercised
    },
    {
        "slug": "stem-coding-kit",
        "name": "STEM Coding Kit",
        "sku": "LM-90218",
        "tone": "purple",
        "competitor": "LittleMindsToys.co.uk",
        "category": "Educational Toys",
        "current_price": 54.99,
        "previous_price": 54.99,
        "change": {"kind": "back", "label": "Back in stock"},
        "in_stock": True,
        "last_change": "10h ago",
        "last_change_minutes": 600,
        "discovered_at": "2026-04-25",
        "source_url": "https://littlemindstoys.co.uk/products/stem-coding-kit",
        "image": None,  # fallback exercised
    },
]

PRODUCT_KPIS = [
    {"id": "total", "label": "Total products", "value": "8,746", "tone": "info"},
    {"id": "new", "label": "New this week", "value": "184", "tone": "success"},
    {"id": "price", "label": "Price changes", "value": "312", "tone": "purple"},
    {"id": "stock", "label": "Stock changes", "value": "97", "tone": "warning"},
    {"id": "removed", "label": "Removed products", "value": "41", "tone": "danger"},
]

PRICE_MOVEMENT = {
    "decreases": 204,
    "increases": 108,
    "series": [
        {"date": "Apr 23", "decreases": 12, "increases": 9},
        {"date": "Apr 26", "decreases": 16, "increases": 11},
        {"date": "Apr 30", "decreases": 19, "increases": 12},
        {"date": "May 3", "decreases": 22, "increases": 10},
        {"date": "May 7", "decreases": 24, "increases": 13},
        {"date": "May 10", "decreases": 27, "increases": 12},
        {"date": "May 14", "decreases": 25, "increases": 14},
        {"date": "May 17", "decreases": 28, "increases": 13},
        {"date": "May 21", "decreases": 31, "increases": 14},
    ],
}

ACTIVE_CATEGORIES = [
    {"name": "Outdoor Toys", "changes": 82},
    {"name": "Educational Toys", "changes": 67},
    {"name": "Construction Toys", "changes": 51},
    {"name": "Plush Toys", "changes": 34},
    {"name": "Baby Toys", "changes": 28},
]

FILTER_OPTIONS = {
    "competitors": [
        "All competitors",
        "ToyWorld.co.uk",
        "PlayNest.co.uk",
        "HappyToyHouse.com",
        "LittleMindsToys.co.uk",
    ],
    "categories": [
        "All categories",
        "Outdoor Toys",
        "Educational Toys",
        "Construction Toys",
        "Baby Toys",
        "Plush Toys",
        "Personalised Toys",
    ],
    "change_types": [
        {"value": "all", "label": "All changes"},
        {"value": "new", "label": "New product"},
        {"value": "drop", "label": "Price decrease"},
        {"value": "increase", "label": "Price increase"},
        {"value": "oos", "label": "Out of stock"},
        {"value": "back", "label": "Back in stock"},
        {"value": "removed", "label": "Removed"},
        {"value": "name", "label": "Name changed"},
        {"value": "category", "label": "Category changed"},
        {"value": "promo", "label": "Promotion detected"},
    ],
    "stock": [
        {"value": "all", "label": "All"},
        {"value": "in", "label": "In stock"},
        {"value": "out", "label": "Out of stock"},
    ],
    "date_ranges": ["Today", "7 days", "30 days", "Custom"],
}

SORT_OPTIONS = [
    {"value": "recent", "label": "Most recent change"},
    {"value": "price-low", "label": "Lowest price"},
    {"value": "price-high", "label": "Highest price"},
    {"value": "biggest-drop", "label": "Biggest price decrease"},
    {"value": "biggest-increase", "label": "Biggest price increase"},
    {"value": "newest", "label": "Newest discovered"},
    {"value": "name", "label": "Product name"},
]
