"""Mock data ported from prototype-react/src/lib/changes-data.ts — deterministic seed for Phase 1."""

CHANGE_COUNT = 4281

CHANGE_EVENTS = [
    {
        "id": 91824,
        "type": "PRICE_DECREASE",
        "kind": "drop",
        "label": "Price decrease",
        "product": {"slug": "lego-castle-set", "name": "LEGO Castle Set", "sku": "TW-10432", "tone": "info", "icon": "blocks"},
        "competitor": "ToyWorld.co.uk",
        "category": "Construction Toys",
        "previous": "£59.99",
        "current": "£49.99",
        "secondary": "-16.7%",
        "secondary_tone": "success",
        "impact": "high",
        "detected": "2h ago",
        "detected_minutes": 120,
        "source_url": "https://toyworld.co.uk/products/lego-castle-set",
        "detected_at": "Today, 11:42",
        "first_seen_at": "Today, 11:42",
        "last_confirmed_at": "Today, 12:12",
        "last_scanned": "12 minutes ago",
        "difference": "-£10.00",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "£59.99", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£49.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "This is one of 42 price reductions detected in Construction and Outdoor Toys today, suggesting a coordinated pricing campaign rather than an isolated adjustment.",
    },
    {
        "id": 91825,
        "type": "PROMOTION_STARTED",
        "kind": "promo",
        "label": "Promotion started",
        "product": {"slug": "stem-robot-kit", "name": "STEM Robot Kit", "sku": "TW-20871", "tone": "purple", "icon": "bot"},
        "competitor": "ToyWorld.co.uk",
        "category": "Educational Toys",
        "previous": "No promotion",
        "current": "20% off",
        "impact": "high",
        "detected": "3h ago",
        "detected_minutes": 180,
        "source_url": "https://toyworld.co.uk/products/stem-robot-kit",
        "detected_at": "Today, 10:36",
        "first_seen_at": "Today, 10:36",
        "last_confirmed_at": "Today, 12:12",
        "last_scanned": "12 minutes ago",
        "evidence": {
            "changed_field": "promotion",
            "previous": {"price": "£39.99", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£39.99", "stock": "In stock", "promotion": "20% off"},
        },
        "ai_note": "ToyWorld started 5 promotions in Educational Toys today. Combined with the Outdoor Toys price cuts, this points to a store-wide seasonal campaign.",
    },
    {
        "id": 91826,
        "type": "STOCK_OUT",
        "kind": "oos",
        "label": "Out of stock",
        "product": {"slug": "wooden-balance-bike", "name": "Wooden Balance Bike", "sku": "TW-30114", "tone": "warning", "icon": "bike"},
        "competitor": "ToyWorld.co.uk",
        "category": "Outdoor Toys",
        "previous": "In stock",
        "current": "Out of stock",
        "impact": "medium",
        "detected": "4h ago",
        "detected_minutes": 240,
        "source_url": "https://toyworld.co.uk/products/wooden-balance-bike",
        "detected_at": "Today, 09:58",
        "first_seen_at": "Today, 09:58",
        "last_confirmed_at": "Today, 12:12",
        "last_scanned": "12 minutes ago",
        "evidence": {
            "changed_field": "stock",
            "previous": {"price": "£89.00", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£89.00", "stock": "Out of stock", "promotion": "None"},
        },
        "ai_note": "Outdoor Toys stock-outs at ToyWorld coincide with their price campaign — high demand may be depleting discounted lines.",
    },
    {
        "id": 91827,
        "type": "PRODUCT_NEW",
        "kind": "new",
        "label": "New product",
        "product": {"slug": "unicorn-plush-xl", "name": "Unicorn Plush XL", "sku": "PN-88214", "tone": "rose", "icon": "rabbit"},
        "competitor": "PlayNest.co.uk",
        "category": "Plush Toys",
        "previous": "Not present",
        "current": "£24.99",
        "impact": "medium",
        "detected": "6h ago",
        "detected_minutes": 360,
        "source_url": "https://playnest.co.uk/products/unicorn-plush-xl",
        "detected_at": "Today, 07:44",
        "first_seen_at": "Today, 07:44",
        "last_confirmed_at": "Today, 11:58",
        "last_scanned": "26 minutes ago",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "—", "stock": "—", "promotion": "—"},
            "current": {"price": "£24.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "PlayNest added 11 new products today, part of a visible catalogue expansion in family and plush categories.",
    },
    {
        "id": 91828,
        "type": "NAME_CHANGED",
        "kind": "name",
        "label": "Name changed",
        "product": {"slug": "personalised-puzzle", "name": "Personalised Puzzle", "sku": "HM-50963", "tone": "teal", "icon": "puzzle"},
        "competitor": "HappyToyHouse.com",
        "category": "Personalised Toys",
        "previous": "Personalised Kids Puzzle",
        "current": "Personalised Wooden Kids Puzzle",
        "impact": "low",
        "detected": "8h ago",
        "detected_minutes": 480,
        "source_url": "https://happytoyhouse.com/products/personalised-puzzle",
        "detected_at": "Today, 05:31",
        "first_seen_at": "Today, 05:31",
        "last_confirmed_at": "Today, 11:12",
        "last_scanned": "1h ago",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "£19.99", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£19.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "Title keyword changes like this usually indicate SEO optimisation rather than a commercial move.",
    },
    {
        "id": 91829,
        "type": "STOCK_BACK",
        "kind": "back",
        "label": "Back in stock",
        "product": {"slug": "stem-coding-kit", "name": "STEM Coding Kit", "sku": "LM-90218", "tone": "purple", "icon": "bot"},
        "competitor": "LittleMindsToys.co.uk",
        "category": "Educational Toys",
        "previous": "Out of stock",
        "current": "In stock",
        "impact": "medium",
        "detected": "10h ago",
        "detected_minutes": 600,
        "source_url": "https://littlemindstoys.co.uk/products/stem-coding-kit",
        "detected_at": "Today, 03:18",
        "first_seen_at": "Today, 03:18",
        "last_confirmed_at": "Today, 11:44",
        "last_scanned": "Scanning now",
        "evidence": {
            "changed_field": "stock",
            "previous": {"price": "£54.99", "stock": "Out of stock", "promotion": "None"},
            "current": {"price": "£54.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "This product was out of stock for 9 days. Restocks in Educational Toys often precede promotional pushes.",
    },
    {
        "id": 91830,
        "type": "PRODUCT_REMOVED",
        "kind": "removed",
        "label": "Removed",
        "product": {"slug": "dinosaur-excavation-kit", "name": "Dinosaur Excavation Kit", "sku": "HM-61220", "tone": "warning", "icon": "bone"},
        "competitor": "HappyToyHouse.com",
        "category": "Educational Toys",
        "previous": "£14.99",
        "current": "Removed",
        "impact": "low",
        "detected": "1d ago",
        "detected_minutes": 1440,
        "source_url": "https://happytoyhouse.com/products/dinosaur-excavation-kit",
        "detected_at": "Yesterday, 16:20",
        "first_seen_at": "Yesterday, 16:20",
        "last_confirmed_at": "Today, 11:12",
        "last_scanned": "1h ago",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "£14.99", "stock": "Out of stock", "promotion": "None"},
            "current": {"price": "—", "stock": "—", "promotion": "—"},
        },
        "ai_note": "The product was missing across several consecutive scans before being classified as removed, so this is unlikely to be a temporary site issue.",
    },
    {
        "id": 91831,
        "type": "VARIANT_ADDED",
        "kind": "variant-add",
        "label": "Variant added",
        "product": {"slug": "wooden-train-set", "name": "Wooden Train Set", "sku": "LM-33871", "tone": "teal", "icon": "train-front"},
        "competitor": "LittleMindsToys.co.uk",
        "category": "Construction Toys",
        "previous": "3 variants",
        "current": "4 variants",
        "impact": "low",
        "detected": "1d ago",
        "detected_minutes": 1560,
        "source_url": "https://littlemindstoys.co.uk/products/wooden-train-set",
        "detected_at": "Yesterday, 14:05",
        "first_seen_at": "Yesterday, 14:05",
        "last_confirmed_at": "Today, 11:44",
        "last_scanned": "Scanning now",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "£32.99", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£32.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "New variants can indicate an upcoming range refresh in Construction Toys.",
    },
    {
        "id": 91832,
        "type": "PRICE_INCREASE",
        "kind": "increase",
        "label": "Price increase",
        "product": {"slug": "garden-water-table", "name": "Garden Water Table", "sku": "PN-11302", "tone": "info", "icon": "baby"},
        "competitor": "PlayNest.co.uk",
        "category": "Outdoor Toys",
        "previous": "£59.99",
        "current": "£64.99",
        "secondary": "+8.3%",
        "secondary_tone": "destructive",
        "impact": "medium",
        "detected": "9h ago",
        "detected_minutes": 540,
        "source_url": "https://playnest.co.uk/products/garden-water-table",
        "detected_at": "Today, 04:47",
        "first_seen_at": "Today, 04:47",
        "last_confirmed_at": "Today, 11:58",
        "last_scanned": "26 minutes ago",
        "difference": "+£5.00",
        "evidence": {
            "changed_field": "price",
            "previous": {"price": "£59.99", "stock": "In stock", "promotion": "None"},
            "current": {"price": "£64.99", "stock": "In stock", "promotion": "None"},
        },
        "ai_note": "PlayNest is raising Outdoor Toys prices while ToyWorld cuts theirs — a widening price gap worth monitoring.",
    },
]

CHANGE_KPIS = [
    {"id": "today", "label": "Changes today", "value": "121", "tone": "info", "icon": "activity"},
    {"id": "decreases", "label": "Price decreases", "value": "64", "tone": "success", "icon": "down"},
    {"id": "increases", "label": "Price increases", "value": "18", "tone": "danger", "icon": "up"},
    {"id": "stock", "label": "Stock changes", "value": "31", "tone": "warning", "icon": "stock"},
    {"id": "new", "label": "New products", "value": "37", "tone": "info", "icon": "new"},
    {"id": "promos", "label": "Promotions", "value": "7", "tone": "purple", "icon": "promo"},
]

CHANGE_PATTERNS = [
    {
        "id": "outdoor-campaign",
        "title": "Outdoor Toys price campaign",
        "competitor": "ToyWorld.co.uk",
        "stat": "42 price reductions",
        "stat_detail": "Average -12.4%",
        "meta": "Last 6 hours",
        "cta": "View 42 changes",
        "icon": "trending-down",
        "tone": "bg-success/10 text-success",
        "filters": {"competitor": "ToyWorld.co.uk", "kind": "drop"},
    },
    {
        "id": "educational-expansion",
        "title": "Educational Toys catalogue expansion",
        "competitor": "PlayNest.co.uk",
        "stat": "14 new products",
        "stat_detail": "Educational Toys",
        "meta": "Today",
        "cta": "View products",
        "icon": "sparkles",
        "tone": "bg-info/10 text-info",
        "filters": {"competitor": "PlayNest.co.uk", "kind": "new"},
    },
    {
        "id": "stock-disruption",
        "title": "Stock disruption",
        "competitor": "HappyToyHouse.com",
        "stat": "18 products out of stock",
        "stat_detail": "Mostly Construction Toys",
        "meta": "Today",
        "cta": "Investigate",
        "icon": "package-x",
        "tone": "bg-warning/10 text-warning",
        "filters": {"competitor": "HappyToyHouse.com", "kind": "oos"},
    },
]

CHANGE_ACTIVITY = [
    {"time": "00:00", "price": 2, "stock": 1, "product": 0, "promotions": 0},
    {"time": "02:00", "price": 1, "stock": 0, "product": 1, "promotions": 0},
    {"time": "04:00", "price": 3, "stock": 2, "product": 2, "promotions": 0},
    {"time": "06:00", "price": 5, "stock": 3, "product": 6, "promotions": 1},
    {"time": "08:00", "price": 9, "stock": 4, "product": 8, "promotions": 1},
    {"time": "10:00", "price": 21, "stock": 7, "product": 9, "promotions": 3},
    {"time": "12:00", "price": 24, "stock": 9, "product": 6, "promotions": 2},
    {"time": "14:00", "price": 11, "stock": 3, "product": 3, "promotions": 0},
    {"time": "16:00", "price": 4, "stock": 1, "product": 1, "promotions": 0},
    {"time": "18:00", "price": 2, "stock": 1, "product": 1, "promotions": 0},
    {"time": "20:00", "price": 0, "stock": 0, "product": 0, "promotions": 0},
    {"time": "22:00", "price": 0, "stock": 0, "product": 0, "promotions": 0},
]

COMPETITOR_ACTIVITY = [
    {"name": "ToyWorld.co.uk", "changes": 67},
    {"name": "PlayNest.co.uk", "changes": 31},
    {"name": "HappyToyHouse.com", "changes": 19},
    {"name": "LittleMindsToys.co.uk", "changes": 4},
]

CHANGE_FILTER_OPTIONS = {
    "competitors": [
        "All competitors",
        "ToyWorld.co.uk",
        "PlayNest.co.uk",
        "HappyToyHouse.com",
        "LittleMindsToys.co.uk",
    ],
    "categories": [
        "All categories",
        "Outdoor Toys",
        "Educational Toys",
        "Construction Toys",
        "Baby Toys",
        "Plush Toys",
        "Personalised Toys",
    ],
    # Backend event types, grouped so the picker stays scannable.
    "change_type_groups": [
        {
            "label": "Pricing",
            "options": [
                {"value": "drop", "label": "Price decrease"},
                {"value": "increase", "label": "Price increase"},
            ],
        },
        {
            "label": "Stock",
            "options": [
                {"value": "oos", "label": "Out of stock"},
                {"value": "back", "label": "Back in stock"},
            ],
        },
        {
            "label": "Products",
            "options": [
                {"value": "new", "label": "New product"},
                {"value": "removed", "label": "Removed product"},
                {"value": "missing", "label": "Missing product"},
            ],
        },
        {
            "label": "Promotions",
            "options": [
                {"value": "promo", "label": "Promotion started"},
                {"value": "promo-end", "label": "Promotion ended"},
            ],
        },
        {
            "label": "Content",
            "options": [
                {"value": "name", "label": "Name changed"},
                {"value": "category", "label": "Category changed"},
                {"value": "description", "label": "Description changed"},
                {"value": "variant-add", "label": "Variant added"},
                {"value": "variant-remove", "label": "Variant removed"},
            ],
        },
    ],
    "importance": [
        {"value": "all", "label": "All importance"},
        {"value": "high", "label": "High"},
        {"value": "medium", "label": "Medium"},
        {"value": "low", "label": "Low"},
    ],
    "date_ranges": ["Today", "24 hours", "7 days", "30 days", "Custom"],
}

CHANGE_SORT_OPTIONS = [
    {"value": "recent", "label": "Most recent"},
    {"value": "impact", "label": "Highest impact"},
    {"value": "biggest-drop", "label": "Biggest price decrease"},
    {"value": "biggest-increase", "label": "Biggest price increase"},
    {"value": "competitor", "label": "Competitor"},
    {"value": "product", "label": "Product"},
]

SAVED_VIEWS = [
    {"id": "drops", "label": "Large Price Drops", "filters": {"kind": "drop", "importance": "high"}},
    {"id": "stock", "label": "Stock Problems", "filters": {"kind": "oos"}},
    {"id": "new", "label": "New Products", "filters": {"kind": "new"}},
    {"id": "promos", "label": "Promotions", "filters": {"kind": "promo"}},
]
