# Generated by Django 5.2.17 on 2026-08-29 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partially_failed', 'Partially failed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('initial', 'Initial'), ('retry', 'Retry')], default='manual', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('changes_detected', models.PositiveIntegerField(default=0)),
                ('pages_requested', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='competitors.competitor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='RawCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=800)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('snippet', models.TextField(blank=True)),
                ('retained_until', models.DateTimeField(blank=True, null=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_captures', to='competitors.competitor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_captures', to='accounts.workspace')),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='scanning.scanjob')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=800)),
                ('url_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('sitemap', 'Sitemap'), ('other', 'Other')], default='product', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('removed', 'Removed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='new', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_urls', to='competitors.competitor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_urls', to='accounts.workspace')),
            ],
            options={
                'ordering': ['url'],
                'indexes': [models.Index(fields=['workspace', 'competitor', 'status'], name='scanning_di_workspa_312c05_idx'), models.Index(fields=['url_hash'], name='scanning_di_url_has_17b265_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'competitor', 'url_hash'), name='unique_discovered_url')],
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['workspace', '-queued_at'], name='scanning_sc_workspa_4d4e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['competitor', '-queued_at'], name='scanning_sc_competi_1e49e8_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status'], name='scanning_sc_status_4ffe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcapture',
            index=models.Index(fields=['workspace', '-fetched_at'], name='scanning_ra_workspa_0db6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='rawcapture',
            index=models.Index(fields=['content_hash'], name='scanning_ra_content_70d981_idx'),
        ),
    ]
