# Generated by Django 5.2.17 on 2026-08-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('competitor_sku', models.CharField(blank=True, max_length=80)),
                ('competitor_product_name', models.CharField(blank=True, max_length=250)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('current_stock_status', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('current_stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_promotion', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('change_kind', models.CharField(blank=True, max_length=20)),
                ('change_label', models.CharField(blank=True, max_length=60)),
                ('last_change_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_change_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('promotion_type', models.CharField(blank=True, max_length=60)),
                ('value', models.CharField(blank=True, max_length=60)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_status', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('unknown', 'Unknown')], max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('own_sku', models.CharField(max_length=80)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('our_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_products', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OwnListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_listings', to='accounts.workspace')),
                ('own_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalogue.ownproduct')),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('captured_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('gtin', models.CharField(blank=True, max_length=14)),
                ('ean', models.CharField(blank=True, max_length=14)),
                ('upc', models.CharField(blank=True, max_length=14)),
                ('mpn', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_products', to='catalogue.product'),
        ),
    ]
