# Generated by Django 5.2.17 on 2026-08-29 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='competitors.competitor'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='pricesnapshot',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='catalogue.productlisting'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.productlisting'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='catalogue.productlisting'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'category'], name='catalogue_p_workspa_629f20_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_product_slug_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='ownproduct',
            constraint=models.UniqueConstraint(fields=('workspace', 'own_sku'), name='unique_own_sku_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['workspace', 'competitor'], name='catalogue_p_workspa_fc7d76_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['product'], name='catalogue_p_product_3e0b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['workspace', 'active'], name='catalogue_p_workspa_7d3eb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='productlisting',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('workspace', 'competitor', 'source_url'), name='unique_listing_source_url'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['listing', '-captured_at'], name='catalogue_p_listing_bf9952_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['workspace', '-captured_at'], name='catalogue_p_workspa_981251_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['listing', 'active'], name='catalogue_p_listing_89adc9_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['workspace', '-captured_at'], name='catalogue_p_workspa_2027d0_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['listing', '-captured_at'], name='catalogue_s_listing_3ca92e_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['workspace', '-captured_at'], name='catalogue_s_workspa_0347ba_idx'),
        ),
    ]
