# Generated by Django 5.2.17 on 2026-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='match_confidence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='match_insight',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
