# Generated by Django 5.2.17 on 2026-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_product_match_confidence_product_match_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='consecutive_misses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
