# Generated by Django 5.2.17 on 2026-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0004_productlisting_consecutive_misses'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'gtin'], name='catalogue_p_workspa_9b7652_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['workspace', 'sku'], name='catalogue_p_workspa_2ff397_idx'),
        ),
    ]
