# Generated by Django 5.2.17 on 2026-08-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0006_trigram_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='ean',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='gtin',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='mpn',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='OwnCatalogueSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('csv', 'CSV'), ('api', 'API')], default='website', max_length=20)),
                ('website_url', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('not_connected', 'Not connected'), ('importing', 'Importing'), ('connected', 'Connected'), ('partial', 'Partially imported'), ('failed', 'Failed')], default='not_connected', max_length=20)),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_sources', to='accounts.workspace')),
            ],
            options={
                'ordering': ['source_type'],
            },
        ),
        migrations.AddField(
            model_name='ownproduct',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.owncataloguesource'),
        ),
        migrations.AddConstraint(
            model_name='owncataloguesource',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_type'), name='unique_source_type_per_workspace'),
        ),
    ]
