# Generated by Django 5.2.17 on 2026-08-29 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0004_productlisting_consecutive_misses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.0)),
                ('method', models.CharField(choices=[('gtin', 'GTIN/EAN/UPC'), ('mpn', 'MPN + brand'), ('sku', 'Exact SKU'), ('brand_model', 'Brand + model'), ('title', 'Title similarity'), ('none', 'No match')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('auto_matched', 'Auto matched'), ('review_required', 'Review required'), ('unmatched', 'Unmatched'), ('rejected', 'Rejected'), ('manually_confirmed', 'Manually confirmed')], default='unmatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_result', to='catalogue.productlisting')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='catalogue.product')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='matching_ma_workspa_43671c_idx'), models.Index(fields=['product'], name='matching_ma_product_70776b_idx')],
            },
        ),
    ]
