# Generated by Django 5.2.17 on 2026-08-29 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('market', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('attention', 'Attention'), ('scanning', 'Scanning'), ('initialising', 'Initialising'), ('paused', 'Paused')], default='initialising', max_length=20)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tone', models.CharField(blank=True, max_length=20)),
                ('products_count', models.PositiveIntegerField(blank=True, null=True)),
                ('changes_today', models.PositiveIntegerField(blank=True, null=True)),
                ('price_drops', models.PositiveIntegerField(blank=True, null=True)),
                ('price_increases', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_changes', models.PositiveIntegerField(blank=True, null=True)),
                ('monitoring_frequency', models.CharField(default='Every 24 hours', max_length=50)),
                ('track_prices', models.BooleanField(default=True)),
                ('track_stock', models.BooleanField(default=True)),
                ('track_products', models.BooleanField(default=True)),
                ('track_promotions', models.BooleanField(default=True)),
                ('added_at', models.DateField(default=django.utils.timezone.localdate)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='competitors_workspa_38c50a_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_competitor_slug_per_workspace'), models.UniqueConstraint(condition=models.Q(('domain', ''), _negated=True), fields=('workspace', 'domain'), name='unique_competitor_domain_per_workspace')],
            },
        ),
    ]
