# Generated by Django 5.2.17 on 2026-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('attention', 'Attention'), ('scanning', 'Scanning'), ('initialising', 'Initialising'), ('paused', 'Paused'), ('blocked', 'Protected')], default='initialising', max_length=20),
        ),
    ]
